image:
  repository: samdidfds/eks-version-exporter
  tag: null
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

serviceMonitor:
  enabled: true

  # -- default release label is prometheus. Change this if you are using a different release name for your Prometheus Operator installation.
  releaseLabel: prometheus

  # -- default interval is 3600s
  interval: 3600s

  # -- default path is /metrics
  path: /metrics
  # -- default metric relabelings
  metricRelabelings:
    - action: keep
      sourceLabels:
        - __name__
      regex: eks_version_exporter|eks_version_exporter_is_outdated|eks_version_exporter_is_past_eol
