image:
  repository: samdidfds/eks-version-exporter
  tag: null
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
namespaceOverride: ""

serviceMonitor:
  enabled: true
  releaseLabel: prometheus
  interval: 3600s

  # -- default path is /metrics, but you can override it if you have a different path
  path: /metrics
  # -- default metric relabelings, but you can override it if you have a different set of metrics
  metricRelabelings:
    - action: keep
      sourceLabels:
        - __name__
      regex: eks_version_exporter|eks_version_exporter_is_outdated|eks_version_exporter_is_past_eol
