apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-version-exporter
  labels:
    app: eks-version-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-version-exporter
  template:
    metadata:
      labels:
        app: eks-version-exporter
    spec:
      containers:
        - name: eks-version-exporter
          image: eks-version-exporter:go
          ports:
            - containerPort: 8080
              name: metrics
