apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: eks-version-exporter
  labels:
    app: eks-version-exporter
    release: prometheus # make it discoverable by prometheus-operator
spec:
  endpoints:
    - path: /metrics
      port: metrics
      metricRelabelings:
        - action: keep
          sourceLabels: [__name__]
          regex: "eks_version_exporter|eks_version_exporter_is_outdated|eks_version_exporter_is_past_eol"
      interval: 3600s # we don't need the resolution more often than daily, so could go higher
  selector:
    matchLabels:
      app: eks-version-exporter
