apiVersion: v1
kind: Service
metadata:
  name: {{ include "eks-version-exporter.fullname" . }}
  namespace: {{ include "eks-version-exporter.namespace" . }}
  labels:
    {{- include "eks-version-exporter.labels" . | nindent 4 }}
    {{- include "eks-version-exporter.selectorLabels" . | nindent 4 }}
spec:
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
  selector:
    {{- include "eks-version-exporter.selectorLabels" . | nindent 4 }}
